"""create spaces and space_memberships tables

Revision ID: 0005_create_spaces
Revises: 0004_create_sessions_table
Create Date: 2026-01-22 14:46:29.978837

"""

import sqlalchemy as sa

from alembic import op

revision = "0005_create_spaces"
down_revision = "0004_create_sessions_table"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spaces",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delete_scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "space_memberships",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "space_id"),
    )
    op.alter_column("sessions", "user_id", existing_type=sa.BIGINT(), type_=sa.Integer(), existing_nullable=False)
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_revoked_at"), table_name="sessions")
    op.drop_constraint(op.f("sessions_token_hash_key"), "sessions", type_="unique")
    op.create_index(op.f("ix_sessions_token_hash"), "sessions", ["token_hash"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_token_hash"), table_name="sessions")
    op.create_unique_constraint(
        op.f("sessions_token_hash_key"), "sessions", ["token_hash"], postgresql_nulls_not_distinct=False
    )
    op.create_index(op.f("ix_sessions_revoked_at"), "sessions", ["revoked_at"], unique=False)
    op.create_index(op.f("ix_sessions_expires_at"), "sessions", ["expires_at"], unique=False)
    op.alter_column("sessions", "user_id", existing_type=sa.Integer(), type_=sa.BIGINT(), existing_nullable=False)
    op.drop_table("space_memberships")
    op.drop_table("spaces")
    # ### end Alembic commands ###
